#! /bin/bash
#  by: Andrew Velez

alias ls='ls --color=auto '
alias ll='ls -Al '
alias l='ls -AlL '
alias where='whereis '
alias sudo='sudo '
alias e='open_file_editor'
alias cat='bat -p -P '
alias bm='bashmatic '
alias v='bat -p '
alias ph='cd $HOME; clear '
alias vadd='sudo xbps-install -S '
alias vfind='sudo xbps-query -Rs '
alias vdel='sudo xbps-remove '
alias vupdate='login_update '
alias vorphans='sudo xbps-remove -Oo '
alias fpu='flatpak update -y && flatpak uninstall --unused '
alias gc='git commit -a -m '
alias gs='git status '
alias latest_updates='v $(ls -t ~/.local/state/vupdate-login/*.log | head -n 1)'