#! /usr/bin/env bash
#  by: Andrew Velez

HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s checkwinsize

if [[ -x /usr/bin/dircolors ]]; then
  (test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)") || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
fi

export TERM="xterm-256color"
export XDG_CONFIG_HOME="$HOME/.config"
export NVM_DIR="$HOME/.local/nvm"
export BUN_INSTALL="$HOME/.local/bun"
export RUSTUP_HOME="$HOME/.local/rustup"
export CARGO_HOME="$HOME/.local/cargo"
export ANDROID_HOME="$HOME/Android/Sdk"
export GOPATH="$HOME/.local/go"
export RUBY_HOME="$HOME/.local/share/gem/ruby/3.4.0"
export RUSTFLAGS="-Clink-arg=-z -Clink-arg=nostart-stop-gc"
export RUSTUP_INIT_SKIP_PATH_CHECK="yes"
export RAD_HOME="$HOME/.radicle"
export FILEN_CLI_DATA_DIR="$XDG_CONFIG_HOME/filen-cli"
export DELTA_FEATURES="diff-so-fancy"
export STOW_DIR="$HOME/Code/dotfiles/stow"
export DOTNET_ROOT='/usr/share/dotnet'
export NUGET_PACKAGES='/usr/share/nuget/packages'
export DOTNET_ADD_GLOBAL_TOOLS_TO_PATH='false'
export SVDIR="$HOME/.local/service"

add_dir_path "PATH" "$HOME/.local/bin"
add_dir_path "PATH" "$HOME/.local/scripts"
add_dir_path "PATH" "$HOME/AppImages"
add_dir_path "PATH" "$DOTNET_ROOT"
add_dir_path "PATH" "$DOTNET_ROOT/tools"
add_dir_path "PATH" "$RUBY_HOME/bin"
add_dir_path "PATH" "/usr/lib/go/bin"
add_dir_path "PATH" "$GOPATH/bin"
add_dir_path "PATH" "$CARGO_HOME/bin"
add_dir_path "PATH" "$BUN_INSTALL/bin"
add_dir_path "PATH" "$HOME/.local/radicle/bin"

add_dir_path "XDG_DATA_DIRS" "/var/lib/flatpak/exports/share"
add_dir_path "XDG_DATA_DIRS" "$HOME/.local/flatpak/exports/share"
add_dir_path "XDG_DATA_DIRS" "$HOME/.local"

add_dir_path "LD_LIBRARY_PATH" "/usr/local/lib"
add_dir_path "LD_LIBRARY_PATH" "/usr/lib"

# Source all the things!
export POSH_THEME="$HOME/.config/posh/gruvbox.omp.json"
type -t "oh-my-posh" > /dev/null && [[ -r "${POSH_THEME}" ]] && eval "$(oh-my-posh init bash --config "${POSH_THEME}")"
type -t "batman" > /dev/null && eval "$(batman --export-env)"
type -t "jj" > /dev/null && eval "$(jj util completion bash)"
[[ -r "$NVM_DIR/nvm.sh" ]] && . "$NVM_DIR/nvm.sh"
[[ -r "$NVM_DIR/bash_completion" ]] && . "$NVM_DIR/bash_completion"
[[ -r "$CARGO_HOME/env" ]] && . "$CARGO_HOME/env"
[[ -r "$HOME/.rbenv/bin/rbenv" ]] && eval "$("$HOME"/.rbenv/bin/rbenv init - --no-rehash bash)"
[[ -r "$HOME/.config/broot/launcher/bash/br" ]] && . "$HOME/.config/broot/launcher/bash/br"

[[ $- == *i* ]] && [[ -r "$HOME/.local/share/blesh/ble.sh" ]] && . "$HOME/.local/share/blesh/ble.sh"
