#! /bin/bash
#  by: Andrew Velez

alias ls='ls --color=auto'
alias l='ls -Al'
alias ll='ls -AlL'
alias where='whereis'
alias sudo='sudo '
alias d='cd'
alias e='open_file_editor'
alias cat='bat -p -P '
alias bm='bashmatic'
alias v='bat -p '

# directory shortcuts
alias ph='cd $HOME; clear'
alias lbin='cd $HOME/.local/bin'

# void specific
alias vadd='sudo xbps-install -S '
alias vfind='sudo xbps-query -Rs '
alias vdel='sudo xbps-remove '
alias vupdate='login_update '
alias vorphans='sudo xbps-remove -Oo '
alias fpu='flatpak update -y && flatpak uninstall --unused '
alias lb='logs_since_boot'

# git
alias ghnew='gh repo create --source=. --remote=origin --push --public'
alias gc='git commit -a -m '
alias gs='git status'
alias gpush='git pull; git push; gs '

# misc
alias python='python3 '
alias mullvad='$HOME/.local/bin/mullvad-wg.sh '
