#! /bin/bash
#  by: Andrew Velez 2026

help() {
    if builtin help "$@" 2> /dev/null; then
        return 0
    fi

    if [[ $# -eq 1 ]] && command -v -- "$1" > /dev/null 2>&1; then
        "$1" --help
        return
    fi

    builtin help "$@"
}

git() {
    if [[ "$1" == "push" ]]; then
        command git pull --ff-only || return
    fi

    command git "$@"
}

open_file_editor() {
    code-oss -r "$@" > /dev/null 2>&1
}

# Source - https://stackoverflow.com/a
# Posted by Rucent88
# Retrieved 2025-12-24, License - CC BY-SA 4.0
sudo_plus() {
    [[ "$(type -t "$1")" == "function" ]] && sudo bash -c "$(declare -f "$1"); $*"
}

img_to_avif() {
    ffmpeg -i "$1" -c:v libaom-av1 -crf 30 -pix_fmt yuv420p "$2"
}
